name: Generate and Commit CSV

on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: "0 12 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Install
        run: npm install

      - name: Run script
        run: node scripts/getLatestData

      - name: Commit and Push CSV
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -f data/ckan-updates.csv data/metaData.json
          git commit -m "Update CSV file" || true  # The script won't fail if there's nothing to commit
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
